### ISSUE TITLE
Change id to identifier

### ISSUE THREAD

**Issue by teodormoq** [scandipwa/menu-organizer#4]
For supporting multiple language site, it should be changed from id to identifier.
Today it doesn't care about what store you use, and if you change the handler to get the menu from identifier would it fix it.

**Comment by alfredsgenkins** [comment]
Thanks! It was completed in one of the previous versions. Use `identifier` to request menu.
https://github.com/scandipwa/menu-organizer/blob/58a11b96cc11a5eaccd4a18bb9b501c77a585e3c/src/etc/schema.graphqls#L11
